version: '2.2'
services:
  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    environment:
 #     - cluster.name=docker-cluster
    #  - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "172.17.0.1:9200:9200"
    networks:
      - elastic-search-service
    restart: unless-stopped
  app:
    image: 'docker.pkg.github.com/l423r/elastic-search-service/elastic-search-service:latest'
    container_name: elastic-search-service
    ports:
      - "172.17.0.1:8085:8085"
    environment:
      - APP_URL=$APP_URL
    networks:
      - elastic-search-service
    restart: unless-stopped
      
volumes:
  esdata:
    driver: local

networks:
  elastic-search-service:
    driver: bridge