version: '3.9'
services:
  elastic-search-service:
    build: .
    container_name: elastic-search-service
    ports:
      - "8085:8085"
    environment:
      - APP_URL=$APP_URL
      - ELASTIC_URL=$ELASTIC_URL
    networks:
      - es
    restart: unless-stopped
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - es
    restart: unless-stopped
      
volumes:
  esdata:

networks:
  es:
    driver: bridge